---
- name: create an ansible user for ec2 instances
  hosts: all
  become: yes
  tasks:
    - name: add ansible user
      ansible.builtin.user:
        name: ansible

    - name: set authorized key
      ansible.posix.authorized_key:
        key: "{{ ansible_user_auth_key }}"
        user: ansible

    - name: enable sudo without password
      ansible.builtin.lineinfile:
        create: yes
        path: /etc/sudoers.d/ansible
        line: 'ansible ALL=(ALL) NOPASSWD: ALL'
