---
- name: manage motd
  hosts: all
  become: yes
  tasks:
    - name: write the motd file to /etc/motd
      template:
        src: templates/motd.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: 0644